pub const PRODUCT_NAME: &str = "TACO";
pub const VERSION_MAJOR: i32 = 0;
pub const VERSION_MINOR: i32 = 6;
pub const VERSION_PATCH: i32 = 0;
pub const VERSION_ALIAS: &str = "Boston";
pub const COPYRIGHT: &str = "Oleg Potapenko";
pub const COPYRIGHT_YEARS: &str = "2024, 2025, 2026";
pub const LICENSE: &str = "MIT";
pub const LINK: &str = "https://github.com/PotapenkoOleg/taco";